debug: false
server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: log4j2-demo
  lifecycle:
    timeout-per-shutdown-phase: 60s
  main:
    lazy-initialization: true
  jmx:
    enabled: false

logging:
  config: classpath:log4j2.yml

